# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef EFL_EINA_BOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
# define EFL_EINA_BOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
#
# include <eina_boost/preprocessor/control/iif.hpp>
#
# /* EFL_EINA_BOOST_PP_AUTO_REC */
#
# define EFL_EINA_BOOST_PP_AUTO_REC(pred, n) EFL_EINA_BOOST_PP_NODE_ENTRY_ ## n(pred)
#
# define EFL_EINA_BOOST_PP_NODE_ENTRY_256(p) EFL_EINA_BOOST_PP_NODE_128(p)(p)(p)(p)(p)(p)(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_128(p) EFL_EINA_BOOST_PP_NODE_64(p)(p)(p)(p)(p)(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_64(p) EFL_EINA_BOOST_PP_NODE_32(p)(p)(p)(p)(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_32(p) EFL_EINA_BOOST_PP_NODE_16(p)(p)(p)(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_16(p) EFL_EINA_BOOST_PP_NODE_8(p)(p)(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_8(p) EFL_EINA_BOOST_PP_NODE_4(p)(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_4(p) EFL_EINA_BOOST_PP_NODE_2(p)(p)
# define EFL_EINA_BOOST_PP_NODE_ENTRY_2(p) EFL_EINA_BOOST_PP_NODE_1(p)
#
# define EFL_EINA_BOOST_PP_NODE_128(p) EFL_EINA_BOOST_PP_IIF(p##(128), EFL_EINA_BOOST_PP_NODE_64, EFL_EINA_BOOST_PP_NODE_192)
#    define EFL_EINA_BOOST_PP_NODE_64(p) EFL_EINA_BOOST_PP_IIF(p##(64), EFL_EINA_BOOST_PP_NODE_32, EFL_EINA_BOOST_PP_NODE_96)
#        define EFL_EINA_BOOST_PP_NODE_32(p) EFL_EINA_BOOST_PP_IIF(p##(32), EFL_EINA_BOOST_PP_NODE_16, EFL_EINA_BOOST_PP_NODE_48)
#            define EFL_EINA_BOOST_PP_NODE_16(p) EFL_EINA_BOOST_PP_IIF(p##(16), EFL_EINA_BOOST_PP_NODE_8, EFL_EINA_BOOST_PP_NODE_24)
#                define EFL_EINA_BOOST_PP_NODE_8(p) EFL_EINA_BOOST_PP_IIF(p##(8), EFL_EINA_BOOST_PP_NODE_4, EFL_EINA_BOOST_PP_NODE_12)
#                    define EFL_EINA_BOOST_PP_NODE_4(p) EFL_EINA_BOOST_PP_IIF(p##(4), EFL_EINA_BOOST_PP_NODE_2, EFL_EINA_BOOST_PP_NODE_6)
#                        define EFL_EINA_BOOST_PP_NODE_2(p) EFL_EINA_BOOST_PP_IIF(p##(2), EFL_EINA_BOOST_PP_NODE_1, EFL_EINA_BOOST_PP_NODE_3)
#                            define EFL_EINA_BOOST_PP_NODE_1(p) EFL_EINA_BOOST_PP_IIF(p##(1), 1, 2)
#                            define EFL_EINA_BOOST_PP_NODE_3(p) EFL_EINA_BOOST_PP_IIF(p##(3), 3, 4)
#                        define EFL_EINA_BOOST_PP_NODE_6(p) EFL_EINA_BOOST_PP_IIF(p##(6), EFL_EINA_BOOST_PP_NODE_5, EFL_EINA_BOOST_PP_NODE_7)
#                            define EFL_EINA_BOOST_PP_NODE_5(p) EFL_EINA_BOOST_PP_IIF(p##(5), 5, 6)
#                            define EFL_EINA_BOOST_PP_NODE_7(p) EFL_EINA_BOOST_PP_IIF(p##(7), 7, 8)
#                    define EFL_EINA_BOOST_PP_NODE_12(p) EFL_EINA_BOOST_PP_IIF(p##(12), EFL_EINA_BOOST_PP_NODE_10, EFL_EINA_BOOST_PP_NODE_14)
#                        define EFL_EINA_BOOST_PP_NODE_10(p) EFL_EINA_BOOST_PP_IIF(p##(10), EFL_EINA_BOOST_PP_NODE_9, EFL_EINA_BOOST_PP_NODE_11)
#                            define EFL_EINA_BOOST_PP_NODE_9(p) EFL_EINA_BOOST_PP_IIF(p##(9), 9, 10)
#                            define EFL_EINA_BOOST_PP_NODE_11(p) EFL_EINA_BOOST_PP_IIF(p##(11), 11, 12)
#                        define EFL_EINA_BOOST_PP_NODE_14(p) EFL_EINA_BOOST_PP_IIF(p##(14), EFL_EINA_BOOST_PP_NODE_13, EFL_EINA_BOOST_PP_NODE_15)
#                            define EFL_EINA_BOOST_PP_NODE_13(p) EFL_EINA_BOOST_PP_IIF(p##(13), 13, 14)
#                            define EFL_EINA_BOOST_PP_NODE_15(p) EFL_EINA_BOOST_PP_IIF(p##(15), 15, 16)
#                define EFL_EINA_BOOST_PP_NODE_24(p) EFL_EINA_BOOST_PP_IIF(p##(24), EFL_EINA_BOOST_PP_NODE_20, EFL_EINA_BOOST_PP_NODE_28)
#                    define EFL_EINA_BOOST_PP_NODE_20(p) EFL_EINA_BOOST_PP_IIF(p##(20), EFL_EINA_BOOST_PP_NODE_18, EFL_EINA_BOOST_PP_NODE_22)
#                        define EFL_EINA_BOOST_PP_NODE_18(p) EFL_EINA_BOOST_PP_IIF(p##(18), EFL_EINA_BOOST_PP_NODE_17, EFL_EINA_BOOST_PP_NODE_19)
#                            define EFL_EINA_BOOST_PP_NODE_17(p) EFL_EINA_BOOST_PP_IIF(p##(17), 17, 18)
#                            define EFL_EINA_BOOST_PP_NODE_19(p) EFL_EINA_BOOST_PP_IIF(p##(19), 19, 20)
#                        define EFL_EINA_BOOST_PP_NODE_22(p) EFL_EINA_BOOST_PP_IIF(p##(22), EFL_EINA_BOOST_PP_NODE_21, EFL_EINA_BOOST_PP_NODE_23)
#                            define EFL_EINA_BOOST_PP_NODE_21(p) EFL_EINA_BOOST_PP_IIF(p##(21), 21, 22)
#                            define EFL_EINA_BOOST_PP_NODE_23(p) EFL_EINA_BOOST_PP_IIF(p##(23), 23, 24)
#                    define EFL_EINA_BOOST_PP_NODE_28(p) EFL_EINA_BOOST_PP_IIF(p##(28), EFL_EINA_BOOST_PP_NODE_26, EFL_EINA_BOOST_PP_NODE_30)
#                        define EFL_EINA_BOOST_PP_NODE_26(p) EFL_EINA_BOOST_PP_IIF(p##(26), EFL_EINA_BOOST_PP_NODE_25, EFL_EINA_BOOST_PP_NODE_27)
#                            define EFL_EINA_BOOST_PP_NODE_25(p) EFL_EINA_BOOST_PP_IIF(p##(25), 25, 26)
#                            define EFL_EINA_BOOST_PP_NODE_27(p) EFL_EINA_BOOST_PP_IIF(p##(27), 27, 28)
#                        define EFL_EINA_BOOST_PP_NODE_30(p) EFL_EINA_BOOST_PP_IIF(p##(30), EFL_EINA_BOOST_PP_NODE_29, EFL_EINA_BOOST_PP_NODE_31)
#                            define EFL_EINA_BOOST_PP_NODE_29(p) EFL_EINA_BOOST_PP_IIF(p##(29), 29, 30)
#                            define EFL_EINA_BOOST_PP_NODE_31(p) EFL_EINA_BOOST_PP_IIF(p##(31), 31, 32)
#            define EFL_EINA_BOOST_PP_NODE_48(p) EFL_EINA_BOOST_PP_IIF(p##(48), EFL_EINA_BOOST_PP_NODE_40, EFL_EINA_BOOST_PP_NODE_56)
#                define EFL_EINA_BOOST_PP_NODE_40(p) EFL_EINA_BOOST_PP_IIF(p##(40), EFL_EINA_BOOST_PP_NODE_36, EFL_EINA_BOOST_PP_NODE_44)
#                    define EFL_EINA_BOOST_PP_NODE_36(p) EFL_EINA_BOOST_PP_IIF(p##(36), EFL_EINA_BOOST_PP_NODE_34, EFL_EINA_BOOST_PP_NODE_38)
#                        define EFL_EINA_BOOST_PP_NODE_34(p) EFL_EINA_BOOST_PP_IIF(p##(34), EFL_EINA_BOOST_PP_NODE_33, EFL_EINA_BOOST_PP_NODE_35)
#                            define EFL_EINA_BOOST_PP_NODE_33(p) EFL_EINA_BOOST_PP_IIF(p##(33), 33, 34)
#                            define EFL_EINA_BOOST_PP_NODE_35(p) EFL_EINA_BOOST_PP_IIF(p##(35), 35, 36)
#                        define EFL_EINA_BOOST_PP_NODE_38(p) EFL_EINA_BOOST_PP_IIF(p##(38), EFL_EINA_BOOST_PP_NODE_37, EFL_EINA_BOOST_PP_NODE_39)
#                            define EFL_EINA_BOOST_PP_NODE_37(p) EFL_EINA_BOOST_PP_IIF(p##(37), 37, 38)
#                            define EFL_EINA_BOOST_PP_NODE_39(p) EFL_EINA_BOOST_PP_IIF(p##(39), 39, 40)
#                    define EFL_EINA_BOOST_PP_NODE_44(p) EFL_EINA_BOOST_PP_IIF(p##(44), EFL_EINA_BOOST_PP_NODE_42, EFL_EINA_BOOST_PP_NODE_46)
#                        define EFL_EINA_BOOST_PP_NODE_42(p) EFL_EINA_BOOST_PP_IIF(p##(42), EFL_EINA_BOOST_PP_NODE_41, EFL_EINA_BOOST_PP_NODE_43)
#                            define EFL_EINA_BOOST_PP_NODE_41(p) EFL_EINA_BOOST_PP_IIF(p##(41), 41, 42)
#                            define EFL_EINA_BOOST_PP_NODE_43(p) EFL_EINA_BOOST_PP_IIF(p##(43), 43, 44)
#                        define EFL_EINA_BOOST_PP_NODE_46(p) EFL_EINA_BOOST_PP_IIF(p##(46), EFL_EINA_BOOST_PP_NODE_45, EFL_EINA_BOOST_PP_NODE_47)
#                            define EFL_EINA_BOOST_PP_NODE_45(p) EFL_EINA_BOOST_PP_IIF(p##(45), 45, 46)
#                            define EFL_EINA_BOOST_PP_NODE_47(p) EFL_EINA_BOOST_PP_IIF(p##(47), 47, 48)
#                define EFL_EINA_BOOST_PP_NODE_56(p) EFL_EINA_BOOST_PP_IIF(p##(56), EFL_EINA_BOOST_PP_NODE_52, EFL_EINA_BOOST_PP_NODE_60)
#                    define EFL_EINA_BOOST_PP_NODE_52(p) EFL_EINA_BOOST_PP_IIF(p##(52), EFL_EINA_BOOST_PP_NODE_50, EFL_EINA_BOOST_PP_NODE_54)
#                        define EFL_EINA_BOOST_PP_NODE_50(p) EFL_EINA_BOOST_PP_IIF(p##(50), EFL_EINA_BOOST_PP_NODE_49, EFL_EINA_BOOST_PP_NODE_51)
#                            define EFL_EINA_BOOST_PP_NODE_49(p) EFL_EINA_BOOST_PP_IIF(p##(49), 49, 50)
#                            define EFL_EINA_BOOST_PP_NODE_51(p) EFL_EINA_BOOST_PP_IIF(p##(51), 51, 52)
#                        define EFL_EINA_BOOST_PP_NODE_54(p) EFL_EINA_BOOST_PP_IIF(p##(54), EFL_EINA_BOOST_PP_NODE_53, EFL_EINA_BOOST_PP_NODE_55)
#                            define EFL_EINA_BOOST_PP_NODE_53(p) EFL_EINA_BOOST_PP_IIF(p##(53), 53, 54)
#                            define EFL_EINA_BOOST_PP_NODE_55(p) EFL_EINA_BOOST_PP_IIF(p##(55), 55, 56)
#                    define EFL_EINA_BOOST_PP_NODE_60(p) EFL_EINA_BOOST_PP_IIF(p##(60), EFL_EINA_BOOST_PP_NODE_58, EFL_EINA_BOOST_PP_NODE_62)
#                        define EFL_EINA_BOOST_PP_NODE_58(p) EFL_EINA_BOOST_PP_IIF(p##(58), EFL_EINA_BOOST_PP_NODE_57, EFL_EINA_BOOST_PP_NODE_59)
#                            define EFL_EINA_BOOST_PP_NODE_57(p) EFL_EINA_BOOST_PP_IIF(p##(57), 57, 58)
#                            define EFL_EINA_BOOST_PP_NODE_59(p) EFL_EINA_BOOST_PP_IIF(p##(59), 59, 60)
#                        define EFL_EINA_BOOST_PP_NODE_62(p) EFL_EINA_BOOST_PP_IIF(p##(62), EFL_EINA_BOOST_PP_NODE_61, EFL_EINA_BOOST_PP_NODE_63)
#                            define EFL_EINA_BOOST_PP_NODE_61(p) EFL_EINA_BOOST_PP_IIF(p##(61), 61, 62)
#                            define EFL_EINA_BOOST_PP_NODE_63(p) EFL_EINA_BOOST_PP_IIF(p##(63), 63, 64)
#        define EFL_EINA_BOOST_PP_NODE_96(p) EFL_EINA_BOOST_PP_IIF(p##(96), EFL_EINA_BOOST_PP_NODE_80, EFL_EINA_BOOST_PP_NODE_112)
#            define EFL_EINA_BOOST_PP_NODE_80(p) EFL_EINA_BOOST_PP_IIF(p##(80), EFL_EINA_BOOST_PP_NODE_72, EFL_EINA_BOOST_PP_NODE_88)
#                define EFL_EINA_BOOST_PP_NODE_72(p) EFL_EINA_BOOST_PP_IIF(p##(72), EFL_EINA_BOOST_PP_NODE_68, EFL_EINA_BOOST_PP_NODE_76)
#                    define EFL_EINA_BOOST_PP_NODE_68(p) EFL_EINA_BOOST_PP_IIF(p##(68), EFL_EINA_BOOST_PP_NODE_66, EFL_EINA_BOOST_PP_NODE_70)
#                        define EFL_EINA_BOOST_PP_NODE_66(p) EFL_EINA_BOOST_PP_IIF(p##(66), EFL_EINA_BOOST_PP_NODE_65, EFL_EINA_BOOST_PP_NODE_67)
#                            define EFL_EINA_BOOST_PP_NODE_65(p) EFL_EINA_BOOST_PP_IIF(p##(65), 65, 66)
#                            define EFL_EINA_BOOST_PP_NODE_67(p) EFL_EINA_BOOST_PP_IIF(p##(67), 67, 68)
#                        define EFL_EINA_BOOST_PP_NODE_70(p) EFL_EINA_BOOST_PP_IIF(p##(70), EFL_EINA_BOOST_PP_NODE_69, EFL_EINA_BOOST_PP_NODE_71)
#                            define EFL_EINA_BOOST_PP_NODE_69(p) EFL_EINA_BOOST_PP_IIF(p##(69), 69, 70)
#                            define EFL_EINA_BOOST_PP_NODE_71(p) EFL_EINA_BOOST_PP_IIF(p##(71), 71, 72)
#                    define EFL_EINA_BOOST_PP_NODE_76(p) EFL_EINA_BOOST_PP_IIF(p##(76), EFL_EINA_BOOST_PP_NODE_74, EFL_EINA_BOOST_PP_NODE_78)
#                        define EFL_EINA_BOOST_PP_NODE_74(p) EFL_EINA_BOOST_PP_IIF(p##(74), EFL_EINA_BOOST_PP_NODE_73, EFL_EINA_BOOST_PP_NODE_75)
#                            define EFL_EINA_BOOST_PP_NODE_73(p) EFL_EINA_BOOST_PP_IIF(p##(73), 73, 74)
#                            define EFL_EINA_BOOST_PP_NODE_75(p) EFL_EINA_BOOST_PP_IIF(p##(75), 75, 76)
#                        define EFL_EINA_BOOST_PP_NODE_78(p) EFL_EINA_BOOST_PP_IIF(p##(78), EFL_EINA_BOOST_PP_NODE_77, EFL_EINA_BOOST_PP_NODE_79)
#                            define EFL_EINA_BOOST_PP_NODE_77(p) EFL_EINA_BOOST_PP_IIF(p##(77), 77, 78)
#                            define EFL_EINA_BOOST_PP_NODE_79(p) EFL_EINA_BOOST_PP_IIF(p##(79), 79, 80)
#                define EFL_EINA_BOOST_PP_NODE_88(p) EFL_EINA_BOOST_PP_IIF(p##(88), EFL_EINA_BOOST_PP_NODE_84, EFL_EINA_BOOST_PP_NODE_92)
#                    define EFL_EINA_BOOST_PP_NODE_84(p) EFL_EINA_BOOST_PP_IIF(p##(84), EFL_EINA_BOOST_PP_NODE_82, EFL_EINA_BOOST_PP_NODE_86)
#                        define EFL_EINA_BOOST_PP_NODE_82(p) EFL_EINA_BOOST_PP_IIF(p##(82), EFL_EINA_BOOST_PP_NODE_81, EFL_EINA_BOOST_PP_NODE_83)
#                            define EFL_EINA_BOOST_PP_NODE_81(p) EFL_EINA_BOOST_PP_IIF(p##(81), 81, 82)
#                            define EFL_EINA_BOOST_PP_NODE_83(p) EFL_EINA_BOOST_PP_IIF(p##(83), 83, 84)
#                        define EFL_EINA_BOOST_PP_NODE_86(p) EFL_EINA_BOOST_PP_IIF(p##(86), EFL_EINA_BOOST_PP_NODE_85, EFL_EINA_BOOST_PP_NODE_87)
#                            define EFL_EINA_BOOST_PP_NODE_85(p) EFL_EINA_BOOST_PP_IIF(p##(85), 85, 86)
#                            define EFL_EINA_BOOST_PP_NODE_87(p) EFL_EINA_BOOST_PP_IIF(p##(87), 87, 88)
#                    define EFL_EINA_BOOST_PP_NODE_92(p) EFL_EINA_BOOST_PP_IIF(p##(92), EFL_EINA_BOOST_PP_NODE_90, EFL_EINA_BOOST_PP_NODE_94)
#                        define EFL_EINA_BOOST_PP_NODE_90(p) EFL_EINA_BOOST_PP_IIF(p##(90), EFL_EINA_BOOST_PP_NODE_89, EFL_EINA_BOOST_PP_NODE_91)
#                            define EFL_EINA_BOOST_PP_NODE_89(p) EFL_EINA_BOOST_PP_IIF(p##(89), 89, 90)
#                            define EFL_EINA_BOOST_PP_NODE_91(p) EFL_EINA_BOOST_PP_IIF(p##(91), 91, 92)
#                        define EFL_EINA_BOOST_PP_NODE_94(p) EFL_EINA_BOOST_PP_IIF(p##(94), EFL_EINA_BOOST_PP_NODE_93, EFL_EINA_BOOST_PP_NODE_95)
#                            define EFL_EINA_BOOST_PP_NODE_93(p) EFL_EINA_BOOST_PP_IIF(p##(93), 93, 94)
#                            define EFL_EINA_BOOST_PP_NODE_95(p) EFL_EINA_BOOST_PP_IIF(p##(95), 95, 96)
#            define EFL_EINA_BOOST_PP_NODE_112(p) EFL_EINA_BOOST_PP_IIF(p##(112), EFL_EINA_BOOST_PP_NODE_104, EFL_EINA_BOOST_PP_NODE_120)
#                define EFL_EINA_BOOST_PP_NODE_104(p) EFL_EINA_BOOST_PP_IIF(p##(104), EFL_EINA_BOOST_PP_NODE_100, EFL_EINA_BOOST_PP_NODE_108)
#                    define EFL_EINA_BOOST_PP_NODE_100(p) EFL_EINA_BOOST_PP_IIF(p##(100), EFL_EINA_BOOST_PP_NODE_98, EFL_EINA_BOOST_PP_NODE_102)
#                        define EFL_EINA_BOOST_PP_NODE_98(p) EFL_EINA_BOOST_PP_IIF(p##(98), EFL_EINA_BOOST_PP_NODE_97, EFL_EINA_BOOST_PP_NODE_99)
#                            define EFL_EINA_BOOST_PP_NODE_97(p) EFL_EINA_BOOST_PP_IIF(p##(97), 97, 98)
#                            define EFL_EINA_BOOST_PP_NODE_99(p) EFL_EINA_BOOST_PP_IIF(p##(99), 99, 100)
#                        define EFL_EINA_BOOST_PP_NODE_102(p) EFL_EINA_BOOST_PP_IIF(p##(102), EFL_EINA_BOOST_PP_NODE_101, EFL_EINA_BOOST_PP_NODE_103)
#                            define EFL_EINA_BOOST_PP_NODE_101(p) EFL_EINA_BOOST_PP_IIF(p##(101), 101, 102)
#                            define EFL_EINA_BOOST_PP_NODE_103(p) EFL_EINA_BOOST_PP_IIF(p##(103), 103, 104)
#                    define EFL_EINA_BOOST_PP_NODE_108(p) EFL_EINA_BOOST_PP_IIF(p##(108), EFL_EINA_BOOST_PP_NODE_106, EFL_EINA_BOOST_PP_NODE_110)
#                        define EFL_EINA_BOOST_PP_NODE_106(p) EFL_EINA_BOOST_PP_IIF(p##(106), EFL_EINA_BOOST_PP_NODE_105, EFL_EINA_BOOST_PP_NODE_107)
#                            define EFL_EINA_BOOST_PP_NODE_105(p) EFL_EINA_BOOST_PP_IIF(p##(105), 105, 106)
#                            define EFL_EINA_BOOST_PP_NODE_107(p) EFL_EINA_BOOST_PP_IIF(p##(107), 107, 108)
#                        define EFL_EINA_BOOST_PP_NODE_110(p) EFL_EINA_BOOST_PP_IIF(p##(110), EFL_EINA_BOOST_PP_NODE_109, EFL_EINA_BOOST_PP_NODE_111)
#                            define EFL_EINA_BOOST_PP_NODE_109(p) EFL_EINA_BOOST_PP_IIF(p##(109), 109, 110)
#                            define EFL_EINA_BOOST_PP_NODE_111(p) EFL_EINA_BOOST_PP_IIF(p##(111), 111, 112)
#                define EFL_EINA_BOOST_PP_NODE_120(p) EFL_EINA_BOOST_PP_IIF(p##(120), EFL_EINA_BOOST_PP_NODE_116, EFL_EINA_BOOST_PP_NODE_124)
#                    define EFL_EINA_BOOST_PP_NODE_116(p) EFL_EINA_BOOST_PP_IIF(p##(116), EFL_EINA_BOOST_PP_NODE_114, EFL_EINA_BOOST_PP_NODE_118)
#                        define EFL_EINA_BOOST_PP_NODE_114(p) EFL_EINA_BOOST_PP_IIF(p##(114), EFL_EINA_BOOST_PP_NODE_113, EFL_EINA_BOOST_PP_NODE_115)
#                            define EFL_EINA_BOOST_PP_NODE_113(p) EFL_EINA_BOOST_PP_IIF(p##(113), 113, 114)
#                            define EFL_EINA_BOOST_PP_NODE_115(p) EFL_EINA_BOOST_PP_IIF(p##(115), 115, 116)
#                        define EFL_EINA_BOOST_PP_NODE_118(p) EFL_EINA_BOOST_PP_IIF(p##(118), EFL_EINA_BOOST_PP_NODE_117, EFL_EINA_BOOST_PP_NODE_119)
#                            define EFL_EINA_BOOST_PP_NODE_117(p) EFL_EINA_BOOST_PP_IIF(p##(117), 117, 118)
#                            define EFL_EINA_BOOST_PP_NODE_119(p) EFL_EINA_BOOST_PP_IIF(p##(119), 119, 120)
#                    define EFL_EINA_BOOST_PP_NODE_124(p) EFL_EINA_BOOST_PP_IIF(p##(124), EFL_EINA_BOOST_PP_NODE_122, EFL_EINA_BOOST_PP_NODE_126)
#                        define EFL_EINA_BOOST_PP_NODE_122(p) EFL_EINA_BOOST_PP_IIF(p##(122), EFL_EINA_BOOST_PP_NODE_121, EFL_EINA_BOOST_PP_NODE_123)
#                            define EFL_EINA_BOOST_PP_NODE_121(p) EFL_EINA_BOOST_PP_IIF(p##(121), 121, 122)
#                            define EFL_EINA_BOOST_PP_NODE_123(p) EFL_EINA_BOOST_PP_IIF(p##(123), 123, 124)
#                        define EFL_EINA_BOOST_PP_NODE_126(p) EFL_EINA_BOOST_PP_IIF(p##(126), EFL_EINA_BOOST_PP_NODE_125, EFL_EINA_BOOST_PP_NODE_127)
#                            define EFL_EINA_BOOST_PP_NODE_125(p) EFL_EINA_BOOST_PP_IIF(p##(125), 125, 126)
#                            define EFL_EINA_BOOST_PP_NODE_127(p) EFL_EINA_BOOST_PP_IIF(p##(127), 127, 128)
#    define EFL_EINA_BOOST_PP_NODE_192(p) EFL_EINA_BOOST_PP_IIF(p##(192), EFL_EINA_BOOST_PP_NODE_160, EFL_EINA_BOOST_PP_NODE_224)
#        define EFL_EINA_BOOST_PP_NODE_160(p) EFL_EINA_BOOST_PP_IIF(p##(160), EFL_EINA_BOOST_PP_NODE_144, EFL_EINA_BOOST_PP_NODE_176)
#            define EFL_EINA_BOOST_PP_NODE_144(p) EFL_EINA_BOOST_PP_IIF(p##(144), EFL_EINA_BOOST_PP_NODE_136, EFL_EINA_BOOST_PP_NODE_152)
#                define EFL_EINA_BOOST_PP_NODE_136(p) EFL_EINA_BOOST_PP_IIF(p##(136), EFL_EINA_BOOST_PP_NODE_132, EFL_EINA_BOOST_PP_NODE_140)
#                    define EFL_EINA_BOOST_PP_NODE_132(p) EFL_EINA_BOOST_PP_IIF(p##(132), EFL_EINA_BOOST_PP_NODE_130, EFL_EINA_BOOST_PP_NODE_134)
#                        define EFL_EINA_BOOST_PP_NODE_130(p) EFL_EINA_BOOST_PP_IIF(p##(130), EFL_EINA_BOOST_PP_NODE_129, EFL_EINA_BOOST_PP_NODE_131)
#                            define EFL_EINA_BOOST_PP_NODE_129(p) EFL_EINA_BOOST_PP_IIF(p##(129), 129, 130)
#                            define EFL_EINA_BOOST_PP_NODE_131(p) EFL_EINA_BOOST_PP_IIF(p##(131), 131, 132)
#                        define EFL_EINA_BOOST_PP_NODE_134(p) EFL_EINA_BOOST_PP_IIF(p##(134), EFL_EINA_BOOST_PP_NODE_133, EFL_EINA_BOOST_PP_NODE_135)
#                            define EFL_EINA_BOOST_PP_NODE_133(p) EFL_EINA_BOOST_PP_IIF(p##(133), 133, 134)
#                            define EFL_EINA_BOOST_PP_NODE_135(p) EFL_EINA_BOOST_PP_IIF(p##(135), 135, 136)
#                    define EFL_EINA_BOOST_PP_NODE_140(p) EFL_EINA_BOOST_PP_IIF(p##(140), EFL_EINA_BOOST_PP_NODE_138, EFL_EINA_BOOST_PP_NODE_142)
#                        define EFL_EINA_BOOST_PP_NODE_138(p) EFL_EINA_BOOST_PP_IIF(p##(138), EFL_EINA_BOOST_PP_NODE_137, EFL_EINA_BOOST_PP_NODE_139)
#                            define EFL_EINA_BOOST_PP_NODE_137(p) EFL_EINA_BOOST_PP_IIF(p##(137), 137, 138)
#                            define EFL_EINA_BOOST_PP_NODE_139(p) EFL_EINA_BOOST_PP_IIF(p##(139), 139, 140)
#                        define EFL_EINA_BOOST_PP_NODE_142(p) EFL_EINA_BOOST_PP_IIF(p##(142), EFL_EINA_BOOST_PP_NODE_141, EFL_EINA_BOOST_PP_NODE_143)
#                            define EFL_EINA_BOOST_PP_NODE_141(p) EFL_EINA_BOOST_PP_IIF(p##(141), 141, 142)
#                            define EFL_EINA_BOOST_PP_NODE_143(p) EFL_EINA_BOOST_PP_IIF(p##(143), 143, 144)
#                define EFL_EINA_BOOST_PP_NODE_152(p) EFL_EINA_BOOST_PP_IIF(p##(152), EFL_EINA_BOOST_PP_NODE_148, EFL_EINA_BOOST_PP_NODE_156)
#                    define EFL_EINA_BOOST_PP_NODE_148(p) EFL_EINA_BOOST_PP_IIF(p##(148), EFL_EINA_BOOST_PP_NODE_146, EFL_EINA_BOOST_PP_NODE_150)
#                        define EFL_EINA_BOOST_PP_NODE_146(p) EFL_EINA_BOOST_PP_IIF(p##(146), EFL_EINA_BOOST_PP_NODE_145, EFL_EINA_BOOST_PP_NODE_147)
#                            define EFL_EINA_BOOST_PP_NODE_145(p) EFL_EINA_BOOST_PP_IIF(p##(145), 145, 146)
#                            define EFL_EINA_BOOST_PP_NODE_147(p) EFL_EINA_BOOST_PP_IIF(p##(147), 147, 148)
#                        define EFL_EINA_BOOST_PP_NODE_150(p) EFL_EINA_BOOST_PP_IIF(p##(150), EFL_EINA_BOOST_PP_NODE_149, EFL_EINA_BOOST_PP_NODE_151)
#                            define EFL_EINA_BOOST_PP_NODE_149(p) EFL_EINA_BOOST_PP_IIF(p##(149), 149, 150)
#                            define EFL_EINA_BOOST_PP_NODE_151(p) EFL_EINA_BOOST_PP_IIF(p##(151), 151, 152)
#                    define EFL_EINA_BOOST_PP_NODE_156(p) EFL_EINA_BOOST_PP_IIF(p##(156), EFL_EINA_BOOST_PP_NODE_154, EFL_EINA_BOOST_PP_NODE_158)
#                        define EFL_EINA_BOOST_PP_NODE_154(p) EFL_EINA_BOOST_PP_IIF(p##(154), EFL_EINA_BOOST_PP_NODE_153, EFL_EINA_BOOST_PP_NODE_155)
#                            define EFL_EINA_BOOST_PP_NODE_153(p) EFL_EINA_BOOST_PP_IIF(p##(153), 153, 154)
#                            define EFL_EINA_BOOST_PP_NODE_155(p) EFL_EINA_BOOST_PP_IIF(p##(155), 155, 156)
#                        define EFL_EINA_BOOST_PP_NODE_158(p) EFL_EINA_BOOST_PP_IIF(p##(158), EFL_EINA_BOOST_PP_NODE_157, EFL_EINA_BOOST_PP_NODE_159)
#                            define EFL_EINA_BOOST_PP_NODE_157(p) EFL_EINA_BOOST_PP_IIF(p##(157), 157, 158)
#                            define EFL_EINA_BOOST_PP_NODE_159(p) EFL_EINA_BOOST_PP_IIF(p##(159), 159, 160)
#            define EFL_EINA_BOOST_PP_NODE_176(p) EFL_EINA_BOOST_PP_IIF(p##(176), EFL_EINA_BOOST_PP_NODE_168, EFL_EINA_BOOST_PP_NODE_184)
#                define EFL_EINA_BOOST_PP_NODE_168(p) EFL_EINA_BOOST_PP_IIF(p##(168), EFL_EINA_BOOST_PP_NODE_164, EFL_EINA_BOOST_PP_NODE_172)
#                    define EFL_EINA_BOOST_PP_NODE_164(p) EFL_EINA_BOOST_PP_IIF(p##(164), EFL_EINA_BOOST_PP_NODE_162, EFL_EINA_BOOST_PP_NODE_166)
#                        define EFL_EINA_BOOST_PP_NODE_162(p) EFL_EINA_BOOST_PP_IIF(p##(162), EFL_EINA_BOOST_PP_NODE_161, EFL_EINA_BOOST_PP_NODE_163)
#                            define EFL_EINA_BOOST_PP_NODE_161(p) EFL_EINA_BOOST_PP_IIF(p##(161), 161, 162)
#                            define EFL_EINA_BOOST_PP_NODE_163(p) EFL_EINA_BOOST_PP_IIF(p##(163), 163, 164)
#                        define EFL_EINA_BOOST_PP_NODE_166(p) EFL_EINA_BOOST_PP_IIF(p##(166), EFL_EINA_BOOST_PP_NODE_165, EFL_EINA_BOOST_PP_NODE_167)
#                            define EFL_EINA_BOOST_PP_NODE_165(p) EFL_EINA_BOOST_PP_IIF(p##(165), 165, 166)
#                            define EFL_EINA_BOOST_PP_NODE_167(p) EFL_EINA_BOOST_PP_IIF(p##(167), 167, 168)
#                    define EFL_EINA_BOOST_PP_NODE_172(p) EFL_EINA_BOOST_PP_IIF(p##(172), EFL_EINA_BOOST_PP_NODE_170, EFL_EINA_BOOST_PP_NODE_174)
#                        define EFL_EINA_BOOST_PP_NODE_170(p) EFL_EINA_BOOST_PP_IIF(p##(170), EFL_EINA_BOOST_PP_NODE_169, EFL_EINA_BOOST_PP_NODE_171)
#                            define EFL_EINA_BOOST_PP_NODE_169(p) EFL_EINA_BOOST_PP_IIF(p##(169), 169, 170)
#                            define EFL_EINA_BOOST_PP_NODE_171(p) EFL_EINA_BOOST_PP_IIF(p##(171), 171, 172)
#                        define EFL_EINA_BOOST_PP_NODE_174(p) EFL_EINA_BOOST_PP_IIF(p##(174), EFL_EINA_BOOST_PP_NODE_173, EFL_EINA_BOOST_PP_NODE_175)
#                            define EFL_EINA_BOOST_PP_NODE_173(p) EFL_EINA_BOOST_PP_IIF(p##(173), 173, 174)
#                            define EFL_EINA_BOOST_PP_NODE_175(p) EFL_EINA_BOOST_PP_IIF(p##(175), 175, 176)
#                define EFL_EINA_BOOST_PP_NODE_184(p) EFL_EINA_BOOST_PP_IIF(p##(184), EFL_EINA_BOOST_PP_NODE_180, EFL_EINA_BOOST_PP_NODE_188)
#                    define EFL_EINA_BOOST_PP_NODE_180(p) EFL_EINA_BOOST_PP_IIF(p##(180), EFL_EINA_BOOST_PP_NODE_178, EFL_EINA_BOOST_PP_NODE_182)
#                        define EFL_EINA_BOOST_PP_NODE_178(p) EFL_EINA_BOOST_PP_IIF(p##(178), EFL_EINA_BOOST_PP_NODE_177, EFL_EINA_BOOST_PP_NODE_179)
#                            define EFL_EINA_BOOST_PP_NODE_177(p) EFL_EINA_BOOST_PP_IIF(p##(177), 177, 178)
#                            define EFL_EINA_BOOST_PP_NODE_179(p) EFL_EINA_BOOST_PP_IIF(p##(179), 179, 180)
#                        define EFL_EINA_BOOST_PP_NODE_182(p) EFL_EINA_BOOST_PP_IIF(p##(182), EFL_EINA_BOOST_PP_NODE_181, EFL_EINA_BOOST_PP_NODE_183)
#                            define EFL_EINA_BOOST_PP_NODE_181(p) EFL_EINA_BOOST_PP_IIF(p##(181), 181, 182)
#                            define EFL_EINA_BOOST_PP_NODE_183(p) EFL_EINA_BOOST_PP_IIF(p##(183), 183, 184)
#                    define EFL_EINA_BOOST_PP_NODE_188(p) EFL_EINA_BOOST_PP_IIF(p##(188), EFL_EINA_BOOST_PP_NODE_186, EFL_EINA_BOOST_PP_NODE_190)
#                        define EFL_EINA_BOOST_PP_NODE_186(p) EFL_EINA_BOOST_PP_IIF(p##(186), EFL_EINA_BOOST_PP_NODE_185, EFL_EINA_BOOST_PP_NODE_187)
#                            define EFL_EINA_BOOST_PP_NODE_185(p) EFL_EINA_BOOST_PP_IIF(p##(185), 185, 186)
#                            define EFL_EINA_BOOST_PP_NODE_187(p) EFL_EINA_BOOST_PP_IIF(p##(187), 187, 188)
#                        define EFL_EINA_BOOST_PP_NODE_190(p) EFL_EINA_BOOST_PP_IIF(p##(190), EFL_EINA_BOOST_PP_NODE_189, EFL_EINA_BOOST_PP_NODE_191)
#                            define EFL_EINA_BOOST_PP_NODE_189(p) EFL_EINA_BOOST_PP_IIF(p##(189), 189, 190)
#                            define EFL_EINA_BOOST_PP_NODE_191(p) EFL_EINA_BOOST_PP_IIF(p##(191), 191, 192)
#        define EFL_EINA_BOOST_PP_NODE_224(p) EFL_EINA_BOOST_PP_IIF(p##(224), EFL_EINA_BOOST_PP_NODE_208, EFL_EINA_BOOST_PP_NODE_240)
#            define EFL_EINA_BOOST_PP_NODE_208(p) EFL_EINA_BOOST_PP_IIF(p##(208), EFL_EINA_BOOST_PP_NODE_200, EFL_EINA_BOOST_PP_NODE_216)
#                define EFL_EINA_BOOST_PP_NODE_200(p) EFL_EINA_BOOST_PP_IIF(p##(200), EFL_EINA_BOOST_PP_NODE_196, EFL_EINA_BOOST_PP_NODE_204)
#                    define EFL_EINA_BOOST_PP_NODE_196(p) EFL_EINA_BOOST_PP_IIF(p##(196), EFL_EINA_BOOST_PP_NODE_194, EFL_EINA_BOOST_PP_NODE_198)
#                        define EFL_EINA_BOOST_PP_NODE_194(p) EFL_EINA_BOOST_PP_IIF(p##(194), EFL_EINA_BOOST_PP_NODE_193, EFL_EINA_BOOST_PP_NODE_195)
#                            define EFL_EINA_BOOST_PP_NODE_193(p) EFL_EINA_BOOST_PP_IIF(p##(193), 193, 194)
#                            define EFL_EINA_BOOST_PP_NODE_195(p) EFL_EINA_BOOST_PP_IIF(p##(195), 195, 196)
#                        define EFL_EINA_BOOST_PP_NODE_198(p) EFL_EINA_BOOST_PP_IIF(p##(198), EFL_EINA_BOOST_PP_NODE_197, EFL_EINA_BOOST_PP_NODE_199)
#                            define EFL_EINA_BOOST_PP_NODE_197(p) EFL_EINA_BOOST_PP_IIF(p##(197), 197, 198)
#                            define EFL_EINA_BOOST_PP_NODE_199(p) EFL_EINA_BOOST_PP_IIF(p##(199), 199, 200)
#                    define EFL_EINA_BOOST_PP_NODE_204(p) EFL_EINA_BOOST_PP_IIF(p##(204), EFL_EINA_BOOST_PP_NODE_202, EFL_EINA_BOOST_PP_NODE_206)
#                        define EFL_EINA_BOOST_PP_NODE_202(p) EFL_EINA_BOOST_PP_IIF(p##(202), EFL_EINA_BOOST_PP_NODE_201, EFL_EINA_BOOST_PP_NODE_203)
#                            define EFL_EINA_BOOST_PP_NODE_201(p) EFL_EINA_BOOST_PP_IIF(p##(201), 201, 202)
#                            define EFL_EINA_BOOST_PP_NODE_203(p) EFL_EINA_BOOST_PP_IIF(p##(203), 203, 204)
#                        define EFL_EINA_BOOST_PP_NODE_206(p) EFL_EINA_BOOST_PP_IIF(p##(206), EFL_EINA_BOOST_PP_NODE_205, EFL_EINA_BOOST_PP_NODE_207)
#                            define EFL_EINA_BOOST_PP_NODE_205(p) EFL_EINA_BOOST_PP_IIF(p##(205), 205, 206)
#                            define EFL_EINA_BOOST_PP_NODE_207(p) EFL_EINA_BOOST_PP_IIF(p##(207), 207, 208)
#                define EFL_EINA_BOOST_PP_NODE_216(p) EFL_EINA_BOOST_PP_IIF(p##(216), EFL_EINA_BOOST_PP_NODE_212, EFL_EINA_BOOST_PP_NODE_220)
#                    define EFL_EINA_BOOST_PP_NODE_212(p) EFL_EINA_BOOST_PP_IIF(p##(212), EFL_EINA_BOOST_PP_NODE_210, EFL_EINA_BOOST_PP_NODE_214)
#                        define EFL_EINA_BOOST_PP_NODE_210(p) EFL_EINA_BOOST_PP_IIF(p##(210), EFL_EINA_BOOST_PP_NODE_209, EFL_EINA_BOOST_PP_NODE_211)
#                            define EFL_EINA_BOOST_PP_NODE_209(p) EFL_EINA_BOOST_PP_IIF(p##(209), 209, 210)
#                            define EFL_EINA_BOOST_PP_NODE_211(p) EFL_EINA_BOOST_PP_IIF(p##(211), 211, 212)
#                        define EFL_EINA_BOOST_PP_NODE_214(p) EFL_EINA_BOOST_PP_IIF(p##(214), EFL_EINA_BOOST_PP_NODE_213, EFL_EINA_BOOST_PP_NODE_215)
#                            define EFL_EINA_BOOST_PP_NODE_213(p) EFL_EINA_BOOST_PP_IIF(p##(213), 213, 214)
#                            define EFL_EINA_BOOST_PP_NODE_215(p) EFL_EINA_BOOST_PP_IIF(p##(215), 215, 216)
#                    define EFL_EINA_BOOST_PP_NODE_220(p) EFL_EINA_BOOST_PP_IIF(p##(220), EFL_EINA_BOOST_PP_NODE_218, EFL_EINA_BOOST_PP_NODE_222)
#                        define EFL_EINA_BOOST_PP_NODE_218(p) EFL_EINA_BOOST_PP_IIF(p##(218), EFL_EINA_BOOST_PP_NODE_217, EFL_EINA_BOOST_PP_NODE_219)
#                            define EFL_EINA_BOOST_PP_NODE_217(p) EFL_EINA_BOOST_PP_IIF(p##(217), 217, 218)
#                            define EFL_EINA_BOOST_PP_NODE_219(p) EFL_EINA_BOOST_PP_IIF(p##(219), 219, 220)
#                        define EFL_EINA_BOOST_PP_NODE_222(p) EFL_EINA_BOOST_PP_IIF(p##(222), EFL_EINA_BOOST_PP_NODE_221, EFL_EINA_BOOST_PP_NODE_223)
#                            define EFL_EINA_BOOST_PP_NODE_221(p) EFL_EINA_BOOST_PP_IIF(p##(221), 221, 222)
#                            define EFL_EINA_BOOST_PP_NODE_223(p) EFL_EINA_BOOST_PP_IIF(p##(223), 223, 224)
#            define EFL_EINA_BOOST_PP_NODE_240(p) EFL_EINA_BOOST_PP_IIF(p##(240), EFL_EINA_BOOST_PP_NODE_232, EFL_EINA_BOOST_PP_NODE_248)
#                define EFL_EINA_BOOST_PP_NODE_232(p) EFL_EINA_BOOST_PP_IIF(p##(232), EFL_EINA_BOOST_PP_NODE_228, EFL_EINA_BOOST_PP_NODE_236)
#                    define EFL_EINA_BOOST_PP_NODE_228(p) EFL_EINA_BOOST_PP_IIF(p##(228), EFL_EINA_BOOST_PP_NODE_226, EFL_EINA_BOOST_PP_NODE_230)
#                        define EFL_EINA_BOOST_PP_NODE_226(p) EFL_EINA_BOOST_PP_IIF(p##(226), EFL_EINA_BOOST_PP_NODE_225, EFL_EINA_BOOST_PP_NODE_227)
#                            define EFL_EINA_BOOST_PP_NODE_225(p) EFL_EINA_BOOST_PP_IIF(p##(225), 225, 226)
#                            define EFL_EINA_BOOST_PP_NODE_227(p) EFL_EINA_BOOST_PP_IIF(p##(227), 227, 228)
#                        define EFL_EINA_BOOST_PP_NODE_230(p) EFL_EINA_BOOST_PP_IIF(p##(230), EFL_EINA_BOOST_PP_NODE_229, EFL_EINA_BOOST_PP_NODE_231)
#                            define EFL_EINA_BOOST_PP_NODE_229(p) EFL_EINA_BOOST_PP_IIF(p##(229), 229, 230)
#                            define EFL_EINA_BOOST_PP_NODE_231(p) EFL_EINA_BOOST_PP_IIF(p##(231), 231, 232)
#                    define EFL_EINA_BOOST_PP_NODE_236(p) EFL_EINA_BOOST_PP_IIF(p##(236), EFL_EINA_BOOST_PP_NODE_234, EFL_EINA_BOOST_PP_NODE_238)
#                        define EFL_EINA_BOOST_PP_NODE_234(p) EFL_EINA_BOOST_PP_IIF(p##(234), EFL_EINA_BOOST_PP_NODE_233, EFL_EINA_BOOST_PP_NODE_235)
#                            define EFL_EINA_BOOST_PP_NODE_233(p) EFL_EINA_BOOST_PP_IIF(p##(233), 233, 234)
#                            define EFL_EINA_BOOST_PP_NODE_235(p) EFL_EINA_BOOST_PP_IIF(p##(235), 235, 236)
#                        define EFL_EINA_BOOST_PP_NODE_238(p) EFL_EINA_BOOST_PP_IIF(p##(238), EFL_EINA_BOOST_PP_NODE_237, EFL_EINA_BOOST_PP_NODE_239)
#                            define EFL_EINA_BOOST_PP_NODE_237(p) EFL_EINA_BOOST_PP_IIF(p##(237), 237, 238)
#                            define EFL_EINA_BOOST_PP_NODE_239(p) EFL_EINA_BOOST_PP_IIF(p##(239), 239, 240)
#                define EFL_EINA_BOOST_PP_NODE_248(p) EFL_EINA_BOOST_PP_IIF(p##(248), EFL_EINA_BOOST_PP_NODE_244, EFL_EINA_BOOST_PP_NODE_252)
#                    define EFL_EINA_BOOST_PP_NODE_244(p) EFL_EINA_BOOST_PP_IIF(p##(244), EFL_EINA_BOOST_PP_NODE_242, EFL_EINA_BOOST_PP_NODE_246)
#                        define EFL_EINA_BOOST_PP_NODE_242(p) EFL_EINA_BOOST_PP_IIF(p##(242), EFL_EINA_BOOST_PP_NODE_241, EFL_EINA_BOOST_PP_NODE_243)
#                            define EFL_EINA_BOOST_PP_NODE_241(p) EFL_EINA_BOOST_PP_IIF(p##(241), 241, 242)
#                            define EFL_EINA_BOOST_PP_NODE_243(p) EFL_EINA_BOOST_PP_IIF(p##(243), 243, 244)
#                        define EFL_EINA_BOOST_PP_NODE_246(p) EFL_EINA_BOOST_PP_IIF(p##(246), EFL_EINA_BOOST_PP_NODE_245, EFL_EINA_BOOST_PP_NODE_247)
#                            define EFL_EINA_BOOST_PP_NODE_245(p) EFL_EINA_BOOST_PP_IIF(p##(245), 245, 246)
#                            define EFL_EINA_BOOST_PP_NODE_247(p) EFL_EINA_BOOST_PP_IIF(p##(247), 247, 248)
#                    define EFL_EINA_BOOST_PP_NODE_252(p) EFL_EINA_BOOST_PP_IIF(p##(252), EFL_EINA_BOOST_PP_NODE_250, EFL_EINA_BOOST_PP_NODE_254)
#                        define EFL_EINA_BOOST_PP_NODE_250(p) EFL_EINA_BOOST_PP_IIF(p##(250), EFL_EINA_BOOST_PP_NODE_249, EFL_EINA_BOOST_PP_NODE_251)
#                            define EFL_EINA_BOOST_PP_NODE_249(p) EFL_EINA_BOOST_PP_IIF(p##(249), 249, 250)
#                            define EFL_EINA_BOOST_PP_NODE_251(p) EFL_EINA_BOOST_PP_IIF(p##(251), 251, 252)
#                        define EFL_EINA_BOOST_PP_NODE_254(p) EFL_EINA_BOOST_PP_IIF(p##(254), EFL_EINA_BOOST_PP_NODE_253, EFL_EINA_BOOST_PP_NODE_255)
#                            define EFL_EINA_BOOST_PP_NODE_253(p) EFL_EINA_BOOST_PP_IIF(p##(253), 253, 254)
#                            define EFL_EINA_BOOST_PP_NODE_255(p) EFL_EINA_BOOST_PP_IIF(p##(255), 255, 256)
#
# endif
