//  (C) Copyright Noel Belcourt 2007.
//  Use, modification and distribution are subject to the
//  Boost Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

//  See http://www.boost.org for most recent version.

//  PGI C++ compiler setup:

#define EFL_EINA_BOOST_COMPILER_VERSION __PGIC__##__PGIC_MINOR__
#define EFL_EINA_BOOST_COMPILER "PGI compiler version " EFL_EINA_BOOST_STRINGIZE(EFL_EINA_BOOST_COMPILER_VERSION)

//
// Threading support:
// Turn this on unconditionally here, it will get turned off again later
// if no threading API is detected.
//

#if __PGIC__ >= 11

// options requested by configure --enable-test
#define EFL_EINA_BOOST_HAS_PTHREADS
#define EFL_EINA_BOOST_HAS_THREADS
#define EFL_EINA_BOOST_HAS_PTHREAD_YIELD
#define EFL_EINA_BOOST_HAS_NRVO
#define EFL_EINA_BOOST_HAS_LONG_LONG

// options --enable-test wants undefined
#undef EFL_EINA_BOOST_NO_STDC_NAMESPACE
#undef EFL_EINA_BOOST_NO_EXCEPTION_STD_NAMESPACE
#undef EFL_EINA_BOOST_DEDUCED_TYPENAME

#define EFL_EINA_BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL
#define EFL_EINA_BOOST_NO_TWO_PHASE_NAME_LOOKUP
#define EFL_EINA_BOOST_NO_CXX11_AUTO_MULTIDECLARATIONS
#define EFL_EINA_BOOST_NO_CXX11_AUTO_DECLARATIONS

#elif __PGIC__ >= 10

// options requested by configure --enable-test
#define EFL_EINA_BOOST_HAS_THREADS
#define EFL_EINA_BOOST_HAS_NRVO
#define EFL_EINA_BOOST_HAS_LONG_LONG
#if defined(linux) || defined(__linux) || defined(__linux__)
#  define EFL_EINA_BOOST_HAS_STDINT_H
#endif

// options --enable-test wants undefined
#undef EFL_EINA_BOOST_NO_STDC_NAMESPACE
#undef EFL_EINA_BOOST_NO_EXCEPTION_STD_NAMESPACE
#undef EFL_EINA_BOOST_DEDUCED_TYPENAME

#elif __PGIC__ >= 7

#define EFL_EINA_BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL
#define EFL_EINA_BOOST_NO_TWO_PHASE_NAME_LOOKUP
#define EFL_EINA_BOOST_NO_SWPRINTF
#define EFL_EINA_BOOST_NO_CXX11_AUTO_MULTIDECLARATIONS
#define EFL_EINA_BOOST_NO_CXX11_AUTO_DECLARATIONS

#else

#  error "Pgi compiler not configured - please reconfigure"

#endif
//
// C++0x features
//
//   See boost\config\suffix.hpp for EFL_EINA_BOOST_NO_LONG_LONG
//
#define EFL_EINA_BOOST_NO_CXX11_CHAR16_T
#define EFL_EINA_BOOST_NO_CXX11_CHAR32_T
#define EFL_EINA_BOOST_NO_CXX11_CONSTEXPR
#define EFL_EINA_BOOST_NO_CXX11_DECLTYPE
#define EFL_EINA_BOOST_NO_CXX11_DECLTYPE_N3276
#define EFL_EINA_BOOST_NO_CXX11_DEFAULTED_FUNCTIONS
#define EFL_EINA_BOOST_NO_CXX11_DELETED_FUNCTIONS
#define EFL_EINA_BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS
#define EFL_EINA_BOOST_NO_CXX11_EXTERN_TEMPLATE
#define EFL_EINA_BOOST_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS
#define EFL_EINA_BOOST_NO_CXX11_LAMBDAS
#define EFL_EINA_BOOST_NO_CXX11_LOCAL_CLASS_TEMPLATE_PARAMETERS
#define EFL_EINA_BOOST_NO_CXX11_NOEXCEPT
#define EFL_EINA_BOOST_NO_CXX11_NULLPTR
#define EFL_EINA_BOOST_NO_CXX11_NUMERIC_LIMITS
#define EFL_EINA_BOOST_NO_CXX11_RANGE_BASED_FOR
#define EFL_EINA_BOOST_NO_CXX11_RAW_LITERALS
#define EFL_EINA_BOOST_NO_CXX11_RVALUE_REFERENCES
#define EFL_EINA_BOOST_NO_CXX11_SCOPED_ENUMS
#define EFL_EINA_BOOST_NO_SFINAE_EXPR
#define EFL_EINA_BOOST_NO_CXX11_STATIC_ASSERT
#define EFL_EINA_BOOST_NO_SWPRINTF
#define EFL_EINA_BOOST_NO_CXX11_TEMPLATE_ALIASES
#define EFL_EINA_BOOST_NO_CXX11_UNICODE_LITERALS
#define EFL_EINA_BOOST_NO_CXX11_VARIADIC_TEMPLATES
#define EFL_EINA_BOOST_NO_CXX11_VARIADIC_MACROS
#define EFL_EINA_BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX

#define EFL_EINA_BOOST_NO_CXX11_HDR_UNORDERED_SET
#define EFL_EINA_BOOST_NO_CXX11_HDR_UNORDERED_MAP
#define EFL_EINA_BOOST_NO_CXX11_HDR_TYPEINDEX
#define EFL_EINA_BOOST_NO_CXX11_HDR_TYPE_TRAITS
#define EFL_EINA_BOOST_NO_CXX11_HDR_TUPLE
#define EFL_EINA_BOOST_NO_CXX11_HDR_THREAD
#define EFL_EINA_BOOST_NO_CXX11_HDR_SYSTEM_ERROR
#define EFL_EINA_BOOST_NO_CXX11_HDR_REGEX
#define EFL_EINA_BOOST_NO_CXX11_HDR_RATIO
#define EFL_EINA_BOOST_NO_CXX11_HDR_RANDOM
#define EFL_EINA_BOOST_NO_CXX11_HDR_MUTEX
#define EFL_EINA_BOOST_NO_CXX11_HDR_INITIALIZER_LIST
#define EFL_EINA_BOOST_NO_CXX11_HDR_FUTURE
#define EFL_EINA_BOOST_NO_CXX11_HDR_FORWARD_LIST
#define EFL_EINA_BOOST_NO_CXX11_HDR_CONDITION_VARIABLE
#define EFL_EINA_BOOST_NO_CXX11_HDR_CODECVT
#define EFL_EINA_BOOST_NO_CXX11_HDR_CHRONO
#define EFL_EINA_BOOST_NO_CXX11_HDR_ARRAY
#define EFL_EINA_BOOST_NO_CXX11_USER_DEFINED_LITERALS
#define EFL_EINA_BOOST_NO_CXX11_ALIGNAS
#define EFL_EINA_BOOST_NO_CXX11_TRAILING_RESULT_TYPES
#define EFL_EINA_BOOST_NO_CXX11_INLINE_NAMESPACES

//
// version check:
// probably nothing to do here?

