
#define EO3_BIG_CLASS eo3_big                                    \
    , function(foo1, _foo, void)                                 \
    , function(foo2, _foo, void)                                 \
    , function(foo3, _foo, void)                                 \
    , function(foo4, _foo, void)                                 \
    , function(foo5, _foo, void)                                 \
    , function(foo6, _foo, void)                                 \
    , function(foo7, _foo, void)                                 \
    , function(foo8, _foo, void)                                 \
    , function(foo9, _foo, void)                                 \
    , function(foo10, _foo, void)                                 \
    , function(foo11, _foo, void)                                 \
    , function(foo12, _foo, void)                                 \
    , function(foo13, _foo, void)                                 \
    , function(foo14, _foo, void)                                 \
    , function(foo15, _foo, void)                                 \
    , function(foo16, _foo, void)                                 \
    , function(foo17, _foo, void)                                 \
    , function(foo18, _foo, void)                                 \
    , function(foo19, _foo, void)                                 \
    , function(foo20, _foo, void)                                 \
    , function(foo21, _foo, void)                                 \
    , function(foo22, _foo, void)                                 \
    , function(foo23, _foo, void)                                 \
    , function(foo24, _foo, void)                                 \
    , function(foo25, _foo, void)                                 \
    , function(foo26, _foo, void)                                 \
    , function(foo27, _foo, void)                                 \
    , function(foo28, _foo, void)                                 \
    , function(foo29, _foo, void)                                 \
    , function(foo30, _foo, void)                                 \
    , function(foo31, _foo, void)                                 \
    , function(foo32, _foo, void)                                 \
    , function(foo33, _foo, void)                                 \
    , function(foo34, _foo, void)                                 \
    , function(foo35, _foo, void)                                 \
    , function(foo36, _foo, void)                                 \
    , function(foo37, _foo, void)                                 \
    , function(foo38, _foo, void)                                 \
    , function(foo39, _foo, void)                                 \
    , function(foo40, _foo, void)                                 \
    , function(foo41, _foo, void)                                 \
    , function(foo42, _foo, void)                                 \
    , function(foo43, _foo, void)                                 \
    , function(foo44, _foo, void)                                 \
    , function(foo45, _foo, void)                                 \
    , function(foo46, _foo, void)                                 \
    , function(foo47, _foo, void)                                 \
    , function(foo48, _foo, void)                                 \
    , function(foo49, _foo, void)                                 \
    , function(foo50, _foo, void)                                 \
    , function(foo51, _foo, void)                                 \
    , function(foo52, _foo, void)                                 \
    , function(foo53, _foo, void)                                 \
    , function(foo54, _foo, void)                                 \
    , function(foo55, _foo, void)                                 \
    , function(foo56, _foo, void)                                 \
    , function(foo57, _foo, void)                                 \
    , function(foo58, _foo, void)                                 \
    , function(foo59, _foo, void)                                 \
    , function(foo60, _foo, void)                                 \
    , function(foo61, _foo, void)                                 \
    , function(foo62, _foo, void)                                 \
    , function(foo63, _foo, void)                                 \
    , function(foo64, _foo, void)                                 \
    , function(foo65, _foo, void)                                 \
    , function(foo66, _foo, void)                                 \
    , function(foo67, _foo, void)                                 \
    , function(foo68, _foo, void)                                 \
    , function(foo69, _foo, void)                                 \
    , function(foo70, _foo, void)                                 \
    , function(foo71, _foo, void)                                 \
    , function(foo72, _foo, void)                                 \
    , function(foo73, _foo, void)                                 \
    , function(foo74, _foo, void)                                 \
    , function(foo75, _foo, void)                                 \
    , function(foo76, _foo, void)                                 \
    , function(foo77, _foo, void)                                 \
    , function(foo78, _foo, void)                                 \
    , function(foo79, _foo, void)                                 \
    , function(foo80, _foo, void)                                 \
    , function(foo81, _foo, void)                                 \
    , function(foo82, _foo, void)                                 \
    , function(foo83, _foo, void)                                 \
    , function(foo84, _foo, void)                                 \
    , function(foo85, _foo, void)                                 \
    , function(foo86, _foo, void)                                 \
    , function(foo87, _foo, void)                                 \
    , function(foo88, _foo, void)                                 \
    , function(foo89, _foo, void)                                 \
    , function(foo90, _foo, void)                                 \
    , function(foo91, _foo, void)                                 \
    , function(foo92, _foo, void)                                 \
    , function(foo93, _foo, void)                                 \
    , function(foo94, _foo, void)                                 \
    , function(foo95, _foo, void)

EO3_DECLARE_CLASS(EO3_BIG_CLASS)
