#ifndef _ECORE_X_ATOMS_H
#define _ECORE_X_ATOMS_H

/**
 * @file
 * @brief Ecore X atoms
 */

/* generic atoms */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_ATOM;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_CARDINAL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_INTEGER; /**< @since 1.24 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_FLOAT; /**< @since 1.24 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_COMPOUND_TEXT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_FILE_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_STRING;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEXT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_UTF8_STRING;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_X_MOZ_URL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WINDOW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_PIXMAP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_VISUALID;

/* dnd atoms */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_XDND;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_PROP_XDND;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_AWARE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ENTER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_TYPE_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_POSITION;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_COPY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_MOVE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_PRIVATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_ASK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_LINK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_ACTION_DESCRIPTION;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_PROXY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_STATUS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_LEAVE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_DROP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_FINISHED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_XDND_DIRECTSAVE0; /**< @since 1.8 */

/* dnd atoms that need to be exposed to the application interface */
EAPI EXTERN Ecore_X_Atom ECORE_X_DND_ACTION_COPY;
EAPI EXTERN Ecore_X_Atom ECORE_X_DND_ACTION_MOVE;
EAPI EXTERN Ecore_X_Atom ECORE_X_DND_ACTION_LINK;
EAPI EXTERN Ecore_X_Atom ECORE_X_DND_ACTION_ASK;
EAPI EXTERN Ecore_X_Atom ECORE_X_DND_ACTION_PRIVATE;

/* old E atom */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_FRAME_SIZE;

/* old Gnome atom */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WIN_LAYER;

/* ICCCM: client properties */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_ICON_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_NORMAL_HINTS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_SIZE_HINTS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_HINTS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_CLASS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_TRANSIENT_FOR;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_PROTOCOLS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_COLORMAP_WINDOWS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_COMMAND;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_CLIENT_MACHINE;

/* ICCCM: window manager properties */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_ICON_SIZE;

/* ICCCM: WM_STATEproperty */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_CHANGE_STATE;

/* ICCCM: WM_PROTOCOLS properties */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_TAKE_FOCUS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_SAVE_YOURSELF;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_DELETE_WINDOW;

/* ICCCM: WM_COLORMAP properties */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_COLORMAP_NOTIFY;

/* ICCCM: session management properties */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SM_CLIENT_ID;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_CLIENT_LEADER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_WM_WINDOW_ROLE;

/* Motif WM atom */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_MOTIF_WM_HINTS;

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_SUPPORTED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_CLIENT_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_CLIENT_LIST_STACKING;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_NUMBER_OF_DESKTOPS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_DESKTOP_GEOMETRY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_DESKTOP_VIEWPORT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_CURRENT_DESKTOP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_DESKTOP_NAMES;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_ACTIVE_WINDOW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WORKAREA;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_SUPPORTING_WM_CHECK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_VIRTUAL_ROOTS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_DESKTOP_LAYOUT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_SHOWING_DESKTOP;

/* pager */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_CLOSE_WINDOW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_MOVERESIZE_WINDOW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_MOVERESIZE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_RESTACK_WINDOW;

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_REQUEST_FRAME_EXTENTS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_VISIBLE_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ICON_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_VISIBLE_ICON_NAME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_DESKTOP;

/* window type */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_DESKTOP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_DOCK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_TOOLBAR;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_MENU;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_UTILITY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_SPLASH;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_DIALOG;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_NORMAL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_DROPDOWN_MENU;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_POPUP_MENU;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_TOOLTIP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_NOTIFICATION;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_COMBO;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_TYPE_DND;

/* state */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_MODAL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_STICKY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_MAXIMIZED_VERT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_MAXIMIZED_HORZ;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_SHADED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_SKIP_TASKBAR;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_SKIP_PAGER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_HIDDEN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_FULLSCREEN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_ABOVE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_BELOW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STATE_DEMANDS_ATTENTION;

/* allowed actions */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ALLOWED_ACTIONS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_MOVE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_RESIZE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_MINIMIZE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_SHADE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_STICK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_MAXIMIZE_HORZ;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_MAXIMIZE_VERT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_FULLSCREEN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_CHANGE_DESKTOP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_CLOSE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_ABOVE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ACTION_BELOW;

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STRUT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_STRUT_PARTIAL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ICON_GEOMETRY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_ICON;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_PID;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_HANDLED_ICONS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_USER_TIME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_STARTUP_ID;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_FRAME_EXTENTS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_PING;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_SYNC_REQUEST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_SYNC_REQUEST_COUNTER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_OPACITY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_SHADOW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_WM_WINDOW_SHADE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_STARTUP_INFO_BEGIN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_NET_STARTUP_INFO;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_TARGETS;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_PRIMARY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_SECONDARY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_CLIPBOARD;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_PROP_PRIMARY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_PROP_SECONDARY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SELECTION_PROP_CLIPBOARD;

/* currently E specific virtual keyboard extension, aim to submit to netwm spec
 * later */

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_ON;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_OFF;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_ALPHA;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_NUMERIC;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_PIN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_PHONE_NUMBER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_HEX;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_TERMINAL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_PASSWORD;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_IP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_HOST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_FILE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_URL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_KEYPAD;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIRTUAL_KEYBOARD_J2ME;

/* Illume specific atoms */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ZONE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ZONE_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_CONFORMANT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_MODE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_MODE_SINGLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_MODE_DUAL_TOP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_MODE_DUAL_LEFT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_FOCUS_BACK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_FOCUS_FORWARD;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_FOCUS_HOME;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_HOME_NEW;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_HOME_DEL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_CLOSE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_DRAG;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_DRAG_LOCKED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_DRAG_START;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_DRAG_END;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_GEOMETRY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_SOFTKEY_GEOMETRY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_KEYBOARD_GEOMETRY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_STATE_TOGGLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_ON;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_OFF;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_PRIORITY_MAJOR;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_PRIORITY_MINOR;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_ZONE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_QUICKPANEL_POSITION_UPDATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_ON;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_OFF;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_OPACITY_MODE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_OPAQUE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_TRANSLUCENT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_TRANSPARENT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_TYPE_MODE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_TYPE_1;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_TYPE_2;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_INDICATOR_TYPE_3;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ROTATE_WINDOW_AVAILABLE_ANGLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ROTATE_WINDOW_ANGLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ROTATE_ROOT_ANGLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_CLIPBOARD_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_CLIPBOARD_ON;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_CLIPBOARD_OFF;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_CLIPBOARD_GEOMETRY;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_WINDOW_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_WINDOW_STATE_NORMAL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_WINDOW_STATE_FLOATING;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_CONTROL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_NEXT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_PREV;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_ACTIVATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_OVER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_READ;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_READ_NEXT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_READ_PREV;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_UP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_DOWN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_BACK;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_SCROLL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_MOUSE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_ENABLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ACTION_DISABLE;

/* Abi compat fix */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_ENABLE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_ACCESS_DISABLE;
/* End of Abi compat fix */

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_SYNC_COUNTER;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_SYNC_DRAW_DONE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_SYNC_SUPPORTED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_SYNC_BEGIN;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_SYNC_END;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_SYNC_CANCEL;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_FLUSH;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_DUMP;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_COMP_PIXMAP;

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIDEO_PARENT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_VIDEO_POSITION;

/* currently elementary and E specific extension */
/* @deprecated use ECORE_X_ATOM_E_WINDOW_PROFILE */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_PROFILE;
/* @deprecated use ECORE_X_ATOM_E_WINDOW_PROFILE_AVAILABLE_LIST */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_PROFILE_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_PROFILE_SUPPORTED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_PROFILE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_PROFILE_CHANGE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_PROFILE_AVAILABLE_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_PROFILE_CHANGE_REQUEST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_PROFILE_CHANGE_DONE;

/* for sliding window */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_SLIDING_WIN_STATE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_ILLUME_SLIDING_WIN_GEOMETRY;

/* for window stacks */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_STACK_TYPE; /**< @since 1.19 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_STACK_POSITION; /**< @since 1.19 */

/* for SDB(Samsung Debug Bridge) */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SDB_SERVER_CONNECT;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_SDB_SERVER_DISCONNECT;

/* for deiconify approve protcol */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_DEICONIFY_APPROVE;

/* E window rotation extension */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_SUPPORTED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_APP_SUPPORTED;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_AVAILABLE_LIST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_PREFERRED_ROTATION;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_CHANGE_PREPARE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_CHANGE_PREPARE_DONE;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_CHANGE_REQUEST;
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_ROTATION_CHANGE_DONE;

/* E window auxiliary hint */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_AUX_HINT_SUPPORTED_LIST; /**< @since 1.10 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_AUX_HINT_SUPPORT; /**< @since 1.10 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_AUX_HINT; /**< @since 1.10 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_WINDOW_AUX_HINT_ALLOWED; /**< @since 1.10 */

/* E keyrouter protocol */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_KEYROUTER_SUPPORTED; /**< @since 1.15 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_E_KEYROUTER_WINDOW_KEYTABLE; /**< @since 1.15 */

/* Teamwork protocol */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_PROPERTY; /**< @since 1.18 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_PRELOAD; /**< @since 1.18 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_ACTIVATE; /**< @since 1.18 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_DEACTIVATE; /**< @since 1.18 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_OPEN; /**< @since 1.18 */

EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_COMPLETED; /**< @since 1.18 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_PROGRESS; /**< @since 1.18 */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_TEAMWORK_STARTED; /**< @since 1.18 */

/* Client-Side Decorations */
EAPI EXTERN Ecore_X_Atom ECORE_X_ATOM_GTK_FRAME_EXTENTS; /**< @since 1.19 */
#endif /* _ECORE_X_ATOMS_H */
