CC=gcc
COMMON_FLAGS=`pkg-config --libs --cflags eina,ecore,eio`

EXAMPLES= emodel_file_example.c

all: examples
examples: $(EXAMPLES)

$(EXAMPLES):
	$(CC) -o $@ $@.c $(COMMON_FLAGS)

clean:
	@echo "Cleaning up built objects..."
	@rm -Rf $(EXAMPLES)
